server:
    port: 8080

spring:
    application:
        name: jobOffers
    data:
        mongodb:
            auto-index-creation: true

    mongodb:
        port: 27017
        host: localhost
        database: job-offers-api
        username: admin
        password: admin
        authentication-database: job-offers-api


job_offers:
    api:
        base-url: http://ec2-18-194-181-208.eu-central-1.compute.amazonaws.com:5057
        connection-timeout: 5000
        read-timeout: 5000
    scheduler:
        enabled: true
        time-cron: "0 0 0 * * ?" # Every day at midnight

