spring.application.name=jobOffers
server.port=8080

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=job-offers-api
spring.mongodb.username=admin
spring.mongodb.password=admin
spring.mongodb.authentication-database=job-offers-api

