server:
    port: 8080

job-offers:
    api:
        base-url: https://fake-java-offers-api.onrender.com
        connection-timeout: 5000
        read-timeout: 5000

    scheduler:
        enabled: true
        time-cron: "0 0 0 * * ?" # Every day at midnight

spring:
    application:
        name: jobOffers
    data:
        mongodb:
            auto-index-creation: true

    mongodb:
        port: 27017
        host: localhost
        database: job-offers-api
        username: admin
        password: admin
        authentication-database: job-offers-api


    cache:
        type: redis
        redis:
            time-to-live: 5 # Time in minutes

    redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:63792}

auth:
    jwt:
        secret-key: ${JWT_SECRET}
        issuer: "JobOffersApi - Backend"
        expiration-time-in-seconds: 720


