spring:
    application:
        name: jobOffers
    data:
        mongodb:
            auto-index-creation: true


job_offers:
    api:
        base-url: http://localhost:8080
    scheduler:
        time-cron: "0 * * * * ?" # Every second