spring:
    application:
        name: jobOffers
    data:
        mongodb:
            auto-index-creation: true


job_offers:
    api:
        base-url: http://localhost:8080
    scheduler:
        enabled: false
        time-cron: "* * * * * ?" # Every second